name: Build and Release

on:
  push:
    branches:
      - main
      - develop

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: '10.10.0'

      - name: Install dependencies
        run: pnpm install

      - name: Build extension
        run: pnpm build

      - name: Create Chrome zip
        run: |
          cd dist
          zip -r ../chrome.zip .
          cd ..

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: chrome-${{ github.sha }}
          path: chrome.zip
          retention-days: 7

      - name: Update Job Summary with Artifact Download Link
        run: |
          echo "## Build succeeded!" >> $GITHUB_STEP_SUMMARY
          echo "- **Commit**: \`${GITHUB_SHA:0:7}\`" >> $GITHUB_STEP_SUMMARY
          echo "- **Artifact Download**: [Download here]($GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID#artifacts)" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "_This build was triggered by a commit on branch **main** or **develop**._" >> $GITHUB_STEP_SUMMARY

  release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: '10.10.0'

      - name: Install dependencies
        run: pnpm install

      - name: Build extension
        run: pnpm build

      - name: Create Firefox zip
        run: |
          node firefox.cjs

      - name: Create Chrome zip
        run: |
          cd dist
          zip -r ../chrome.zip .
          cd ..

      - name: Get short SHA and timestamp
        id: vars
        run: |
          echo "SHORT_SHA=$(echo $GITHUB_SHA | cut -c1-8)" >> $GITHUB_ENV
          echo "TIMESTAMP=$(date +'%Y%m%d-%H%M%S')" >> $GITHUB_ENV

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: release
          name: Release ${{ env.SHORT_SHA }}
          body: |
            ## Miro Extension Release
            
            **Commit**: `${{ github.sha }}`  
            **Branch**: `${{ github.ref_name }}`  
            **Build Time**: ${{ env.TIMESTAMP }}
            
            ### Downloads
            - **Chrome/Edge**: Download `chrome.zip`
            - **Firefox**: Download `firefox.zip`
            
            ### Installation
            1. Download the appropriate zip file for your browser
            2. Extract the zip file
            3. Load the extension in developer mode
            
            For detailed installation instructions, see the [README](https://github.com/${{ github.repository }}/blob/main/README.md).
          draft: false
          prerelease: false
          files: |
            firefox.zip
            chrome.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
